### ISSUE TITLE
Feature Request: New Inertia Constructor Supporting Parsed Template

### ISSUE THREAD

**Issue by ge3224** [romsar/gonertia#26]
## Problem

The current Gonertia library only supports creating an Inertia instance using a `rootTemplateHTML` field. This limits flexibility for projects that have already parsed template files into a `*template.Template`.

## Proposed Solution

Add a new constructor method:

```go
func NewFromTemplate(t *template.Template, opts ...Option) (*Inertia, error)
```

## Rationale

- Enables integration with existing template parsing workflows
- Provides more flexible initialization for complex template setups
- Reduces redundant template parsing

### Implementation Notes

- The existing [`doHTMLResponse`](https://github.com/romsar/gonertia/blob/e05cf883412ca23fbc11918f5fcf990d2b89acab/response.go#L273) method already skips using `rootTemplateHTML` if `rootTemplate` is non-nil
- This means the new constructor can directly set `rootTemplate` without breaking existing logic

## Example Use Case

```go
tmpl := template.Must(template.ParseFiles("layout.html", "components.html"))
inertia, err := NewFromTemplate(tmpl, 
    WithSharedProps(props),
    WithVersion("1.0")
)
```

## Contribution

If desired, I'm willing to create a pull request implementing this feature, including unit tests.

**Comment by romsar** [comment]
It's a very interesting idea, let's do it.
I think you can make a pull request to the v2.x branch, it will become the main branch soon.
