### ISSUE TITLE
Error for import of v2

### ISSUE THREAD

**Issue by HeldvonKosmos** [romsar/gonertia#31]
I got an error for import.

I have specified it in go.mod like this "github.com/romsar/gonertia v2.0.1"

[root@02478b280c1e root]# go mod tidy
go: errors parsing go.mod:
go.mod:13:5: require github.com/romsar/gonertia: version "v2.0.1" invalid: should be v0 or v1, not v2

**Comment by romsar** [comment]
Thanks for reporting this issue. Fixed.
Now you have to import github.com/romsar/gonertia/v2
